
package view;

import controller.AuthenticationController;
import javax.swing.JOptionPane;
import models.AuthenticationModel;

public class LoginScreen extends javax.swing.JFrame {

   
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heroBackground = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        slogon = new javax.swing.JLabel();
        loginText = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        roleLabel = new javax.swing.JLabel();
        roleDropDown = new javax.swing.JComboBox<>();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();
        loginNavigationText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        heroBackground.setBackground(new java.awt.Color(102, 0, 102));
        heroBackground.setToolTipText("");

        welcomeText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(255, 255, 255));
        welcomeText.setText("Welcome To Event Planing System");

        slogon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        slogon.setForeground(new java.awt.Color(255, 255, 255));
        slogon.setText("Turning Moments into Memories – Seamlessly!");

        javax.swing.GroupLayout heroBackgroundLayout = new javax.swing.GroupLayout(heroBackground);
        heroBackground.setLayout(heroBackgroundLayout);
        heroBackgroundLayout.setHorizontalGroup(
            heroBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heroBackgroundLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(heroBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, heroBackgroundLayout.createSequentialGroup()
                        .addComponent(welcomeText)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, heroBackgroundLayout.createSequentialGroup()
                        .addComponent(slogon)
                        .addGap(172, 172, 172))))
        );
        heroBackgroundLayout.setVerticalGroup(
            heroBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(heroBackgroundLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(welcomeText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slogon)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        loginText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginText.setForeground(new java.awt.Color(102, 0, 102));
        loginText.setText("LOGIN");

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 0, 0));
        emailLabel.setText("Email:");

        roleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(0, 0, 0));
        roleLabel.setText("Role:");

        roleDropDown.setBackground(new java.awt.Color(255, 255, 255));
        roleDropDown.setForeground(new java.awt.Color(0, 0, 0));
        roleDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Event Manager", "Vendor" }));
        roleDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleDropDownActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(0, 0, 0));
        passwordLabel.setText("Password:");

        LoginButton.setBackground(new java.awt.Color(102, 0, 102));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        loginLabel.setForeground(new java.awt.Color(0, 0, 0));
        loginLabel.setText("Don't Have an Account?");

        loginNavigationText.setForeground(new java.awt.Color(102, 0, 102));
        loginNavigationText.setText("Signup");
        loginNavigationText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginNavigationTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(heroBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(loginText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel)
                            .addComponent(emailLabel)
                            .addComponent(roleLabel))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailTextField)
                            .addComponent(passwordTextField)
                            .addComponent(roleDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loginLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(loginNavigationText))
                            .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(231, 231, 231))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(heroBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginText)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleLabel)
                    .addComponent(roleDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(loginNavigationText))
                .addGap(0, 69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roleDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleDropDownActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed

        String email = emailTextField.getText();
        String password = new String(passwordTextField.getPassword());
        String role = (String) roleDropDown.getSelectedItem();

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (role == null || role.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Role must be selected.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (password.length() < 6) {
            JOptionPane.showMessageDialog(null, "Password must be at least 6 characters.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        AuthenticationModel authModel = new AuthenticationModel(email, password, role);

        boolean isAuthenticated = AuthenticationController.authenticateUser(authModel);

        if (isAuthenticated) {
            JOptionPane.showMessageDialog(null, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false); 
        } else {
            JOptionPane.showMessageDialog(null, "Invalid email or password.", "Authentication Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void loginNavigationTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginNavigationTextMouseClicked
        this.setVisible(false);

        SignupScreen signupScreen = new SignupScreen();
        signupScreen.setVisible(true);    }//GEN-LAST:event_loginNavigationTextMouseClicked

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel heroBackground;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginNavigationText;
    private javax.swing.JLabel loginText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JComboBox<String> roleDropDown;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel slogon;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
